services:
  db:
    container_name: todomyrberg_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todomyrberg
    volumes:
      - todomyrberg_pg_data:/var/lib/postgresql/data
    networks:
      - todomyrberg_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todomyrberg"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: todomyrberg_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todomyrberg
      - PORT=5000
    ports:
      - "5050:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todomyrberg_net
    volumes:
      - ./backend:/app/backend

networks:
  todomyrberg_net:
    name: todomyrberg_net

volumes:
  todomyrberg_pg_data:
    name: todomyrberg_pg_data
    external: true
